import user.*; 
import acc.*; 
import java.util.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
 *
 * @author admin
 */
public class MainFrame extends javax.swing.JFrame {
    UserDAO userDAO = new UserDAO();
    User user = new User();
    
    AccDAO accDAO = new AccDAO();
    Acc acc = new Acc();
    
    String strSQL = "";
    
    String userID = null;
    
    Calendar today = Calendar.getInstance();
    
    String year = Integer.toString(today.get(Calendar.YEAR));
    String month = Integer.toString(today.get(Calendar.MONTH) + 1);
    String day = Integer.toString(today.get(Calendar.DATE));
    
    public void dateChange() {
        lblTodayList1.setText(lblDateView.getText() + " 의 목록");
        lblTodayList.setText(lblDateView.getText() + " 의 수입");
        lblTodayList2.setText(lblDateView.getText() + " 의 지출");
   }
    
    public void viewDateChange() {
        lblDateView.setText(cbxYear.getSelectedItem().toString() + "-" + cbxMonth.getSelectedItem().toString() + "-" + cbxDay.getSelectedItem().toString());
        dateChange();
   }
    /*
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        lblDateView.setText(cbxYear.getSelectedItem().toString() + "-" + cbxMonth.getSelectedItem().toString() + "-" + cbxDay.getSelectedItem().toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginFrame = new javax.swing.JFrame();
        lblId = new javax.swing.JLabel();
        lblPw = new javax.swing.JLabel();
        tfdId = new javax.swing.JTextField();
        btnLogFromLogin = new javax.swing.JButton();
        pwfPw = new javax.swing.JPasswordField();
        SigninFrame = new javax.swing.JFrame();
        lblNewId = new javax.swing.JLabel();
        lblNewPw = new javax.swing.JLabel();
        tfdNewPw = new javax.swing.JTextField();
        btnSingFormSignin = new javax.swing.JButton();
        lblNewName = new javax.swing.JLabel();
        lblNewPwCheck = new javax.swing.JLabel();
        lblNewProperty = new javax.swing.JLabel();
        tfdNewName = new javax.swing.JTextField();
        tfdNewProperty = new javax.swing.JTextField();
        btnNewIdCheck = new javax.swing.JButton();
        tfdNewId = new javax.swing.JTextField();
        tfdNewPwCheck = new javax.swing.JTextField();
        Main = new javax.swing.JFrame();
        MainPane = new javax.swing.JTabbedPane();
        paneWrite = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        cbxYear = new javax.swing.JComboBox<>();
        lblYear = new javax.swing.JLabel();
        cbxDay = new javax.swing.JComboBox<>();
        lblDay = new javax.swing.JLabel();
        cbxMonth = new javax.swing.JComboBox<>();
        lblMonth = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblItem = new javax.swing.JLabel();
        lblDiv = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblMemo = new javax.swing.JLabel();
        lblDateView = new javax.swing.JLabel();
        rbtnIncome = new javax.swing.JRadioButton();
        rbtnExpen = new javax.swing.JRadioButton();
        rbtnSaving = new javax.swing.JRadioButton();
        cbxItem = new javax.swing.JComboBox<>();
        tfdPrice = new javax.swing.JTextField();
        cbxType = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarMemo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarTodayList = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tarTodayExpen = new javax.swing.JTextArea();
        btnRefresh = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tarTodayIncome = new javax.swing.JTextArea();
        choiceDate = new javax.swing.JLabel();
        btnDeleteAll = new javax.swing.JButton();
        lblTodayList = new javax.swing.JLabel();
        lblTodayList1 = new javax.swing.JLabel();
        lblTodayList2 = new javax.swing.JLabel();
        paneStat = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tarSearchView = new javax.swing.JTextArea();
        cbxSearchYear1 = new javax.swing.JComboBox<>();
        cbxSearchMonth1 = new javax.swing.JComboBox<>();
        cbxSearchYear2 = new javax.swing.JComboBox<>();
        cbxSearchMonth2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSearchAll = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblExpen1 = new javax.swing.JLabel();
        lblExpen3 = new javax.swing.JLabel();
        lblExpenPrice1 = new javax.swing.JLabel();
        lblExpenPrice2 = new javax.swing.JLabel();
        lblExpenPrice3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblAllCount = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblExpenPrice = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblIncomePrice = new javax.swing.JLabel();
        btnExit2 = new javax.swing.JButton();
        lblExpen2 = new javax.swing.JLabel();
        paneList = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tarListViewFilter = new javax.swing.JTextArea();
        btnView = new javax.swing.JButton();
        cbxFilter = new javax.swing.JComboBox<>();
        btnExit3 = new javax.swing.JButton();
        btnGrpDivision = new javax.swing.ButtonGroup();
        btnLogin = new javax.swing.JButton();
        btnSignin = new javax.swing.JButton();

        LoginFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        LoginFrame.setTitle("로그인");
        LoginFrame.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N

        lblId.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblId.setText("아이디");

        lblPw.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblPw.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPw.setText("비밀번호");

        tfdId.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N

        btnLogFromLogin.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btnLogFromLogin.setText("로그인");
        btnLogFromLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogFromLoginActionPerformed(evt);
            }
        });

        pwfPw.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N

        javax.swing.GroupLayout LoginFrameLayout = new javax.swing.GroupLayout(LoginFrame.getContentPane());
        LoginFrame.getContentPane().setLayout(LoginFrameLayout);
        LoginFrameLayout.setHorizontalGroup(
            LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFrameLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnLogFromLogin)
                        .addGroup(LoginFrameLayout.createSequentialGroup()
                            .addComponent(lblId)
                            .addGap(32, 32, 32)
                            .addComponent(tfdId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LoginFrameLayout.createSequentialGroup()
                        .addComponent(lblPw)
                        .addGap(18, 18, 18)
                        .addComponent(pwfPw, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        LoginFrameLayout.setVerticalGroup(
            LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFrameLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(tfdId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPw)
                    .addComponent(pwfPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogFromLogin)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        SigninFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        SigninFrame.setTitle("회원가입");
        SigninFrame.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N

        lblNewId.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblNewId.setText("아이디");

        lblNewPw.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblNewPw.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNewPw.setText("비밀번호");

        tfdNewPw.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N

        btnSingFormSignin.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btnSingFormSignin.setText("회원가입");
        btnSingFormSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingFormSigninActionPerformed(evt);
            }
        });

        lblNewName.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblNewName.setText("이름");

        lblNewPwCheck.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblNewPwCheck.setText("비밀번호 확인");

        lblNewProperty.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblNewProperty.setText("초기보유자금");

        tfdNewName.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N

        tfdNewProperty.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N

        btnNewIdCheck.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btnNewIdCheck.setText("중복확인");
        btnNewIdCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewIdCheckActionPerformed(evt);
            }
        });

        tfdNewId.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N

        tfdNewPwCheck.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N

        javax.swing.GroupLayout SigninFrameLayout = new javax.swing.GroupLayout(SigninFrame.getContentPane());
        SigninFrame.getContentPane().setLayout(SigninFrameLayout);
        SigninFrameLayout.setHorizontalGroup(
            SigninFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SigninFrameLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(SigninFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SigninFrameLayout.createSequentialGroup()
                        .addComponent(lblNewId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfdNewId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SigninFrameLayout.createSequentialGroup()
                        .addComponent(lblNewName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfdNewName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SigninFrameLayout.createSequentialGroup()
                        .addComponent(lblNewPw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfdNewPw, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SigninFrameLayout.createSequentialGroup()
                        .addGroup(SigninFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNewPwCheck)
                            .addComponent(lblNewProperty))
                        .addGap(31, 31, 31)
                        .addGroup(SigninFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfdNewProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdNewPwCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSingFormSignin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addComponent(btnNewIdCheck)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        SigninFrameLayout.setVerticalGroup(
            SigninFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SigninFrameLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(SigninFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewName)
                    .addComponent(tfdNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SigninFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewId)
                    .addComponent(btnNewIdCheck)
                    .addComponent(tfdNewId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SigninFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPw)
                    .addComponent(tfdNewPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(SigninFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPwCheck)
                    .addComponent(tfdNewPwCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SigninFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewProperty)
                    .addComponent(tfdNewProperty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSingFormSignin)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        Main.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Main.setTitle("가계부 v0.1");
        Main.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N

        MainPane.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        MainPane.setPreferredSize(new java.awt.Dimension(1300, 712));

        paneWrite.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N

        lblWelcome.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cbxYear.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        cbxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        cbxYear.setSelectedIndex(2);
        cbxYear.setSelectedItem(year);
        cbxYear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxYearItemStateChanged(evt);
            }
        });

        lblYear.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblYear.setText("년");

        cbxDay.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        cbxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbxDay.setSelectedItem(day);
        cbxDay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxDayItemStateChanged(evt);
            }
        });

        lblDay.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblDay.setText("일");

        cbxMonth.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        cbxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbxMonth.setSelectedItem(month);
        cbxMonth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMonthItemStateChanged(evt);
            }
        });

        lblMonth.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblMonth.setText("월");

        lblDate.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblDate.setText("날짜");

        lblItem.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblItem.setText("항목");

        lblDiv.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblDiv.setText("구분");

        lblType.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblType.setText("유형");

        jLabel10.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel10.setText("금액");

        lblMemo.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblMemo.setText("메모");

        lblDateView.setBackground(new java.awt.Color(255, 255, 255));
        lblDateView.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        lblDateView.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDateView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnGrpDivision.add(rbtnIncome);
        rbtnIncome.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        rbtnIncome.setSelected(true);
        rbtnIncome.setText("수입");
        rbtnIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnIncomeActionPerformed(evt);
            }
        });

        btnGrpDivision.add(rbtnExpen);
        rbtnExpen.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        rbtnExpen.setText("지출");
        rbtnExpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnExpenActionPerformed(evt);
            }
        });

        btnGrpDivision.add(rbtnSaving);
        rbtnSaving.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        rbtnSaving.setText("저축");
        rbtnSaving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSavingActionPerformed(evt);
            }
        });

        cbxItem.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N

        tfdPrice.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        tfdPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cbxType.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        cbxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "수입", "저축", "충동적소비", "계획적소비", "필수적소비" }));

        tarMemo.setColumns(20);
        tarMemo.setRows(5);
        jScrollPane1.setViewportView(tarMemo);

        tarTodayList.setEditable(false);
        tarTodayList.setColumns(20);
        tarTodayList.setRows(5);
        tarTodayList.setTabSize(10);
        jScrollPane2.setViewportView(tarTodayList);

        tarTodayExpen.setEditable(false);
        tarTodayExpen.setColumns(20);
        tarTodayExpen.setRows(5);
        tarTodayExpen.setTabSize(10);
        jScrollPane3.setViewportView(tarTodayExpen);

        btnRefresh.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btnRefresh.setText("새로고침");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnExit1.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btnExit1.setText("프로그램 종료");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        btnUpload.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btnUpload.setText("등록");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btnReset.setText("초기화");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tarTodayIncome.setEditable(false);
        tarTodayIncome.setColumns(20);
        tarTodayIncome.setRows(5);
        tarTodayIncome.setTabSize(10);
        jScrollPane5.setViewportView(tarTodayIncome);

        choiceDate.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        choiceDate.setText("날짜선택");

        btnDeleteAll.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btnDeleteAll.setText("전체삭제");
        btnDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllActionPerformed(evt);
            }
        });

        lblTodayList.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        lblTodayList.setText("2021-11-26 의 목록");

        lblTodayList1.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        lblTodayList1.setText("2021-11-26 의 목록");
        lblTodayList1.setToolTipText("");

        lblTodayList2.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        lblTodayList2.setText("2021-11-26 의 목록");

        javax.swing.GroupLayout paneWriteLayout = new javax.swing.GroupLayout(paneWrite);
        paneWrite.setLayout(paneWriteLayout);
        paneWriteLayout.setHorizontalGroup(
            paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneWriteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneWriteLayout.createSequentialGroup()
                        .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneWriteLayout.createSequentialGroup()
                                .addComponent(lblItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(213, 213, 213))
                            .addGroup(paneWriteLayout.createSequentialGroup()
                                .addComponent(choiceDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(256, 256, 256))
                            .addGroup(paneWriteLayout.createSequentialGroup()
                                .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMemo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(paneWriteLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rbtnSaving)
                                            .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblDateView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(paneWriteLayout.createSequentialGroup()
                                                    .addComponent(cbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lblYear)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(cbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lblMonth)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(cbxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lblDay)))))
                                    .addGroup(paneWriteLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane1)
                                                .addComponent(cbxType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tfdPrice)
                                                .addGroup(paneWriteLayout.createSequentialGroup()
                                                    .addComponent(rbtnIncome)
                                                    .addGap(49, 49, 49)
                                                    .addComponent(rbtnExpen))
                                                .addComponent(cbxItem, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnUpload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))))
                                    .addGroup(paneWriteLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, Short.MAX_VALUE)))
                        .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneWriteLayout.createSequentialGroup()
                                .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(paneWriteLayout.createSequentialGroup()
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnExit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeleteAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(paneWriteLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(lblTodayList)
                                .addGap(191, 191, 191)
                                .addComponent(lblTodayList2))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneWriteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTodayList1)
                        .addGap(399, 399, 399)))
                .addGap(311, 311, 311))
        );
        paneWriteLayout.setVerticalGroup(
            paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneWriteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTodayList1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneWriteLayout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addGap(284, 284, 284)
                        .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExit1)
                            .addGroup(paneWriteLayout.createSequentialGroup()
                                .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTodayList2)
                                    .addComponent(lblTodayList))
                                .addGap(18, 18, 18)
                                .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(paneWriteLayout.createSequentialGroup()
                        .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneWriteLayout.createSequentialGroup()
                                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(choiceDate)
                                    .addComponent(lblYear)
                                    .addComponent(lblMonth)
                                    .addComponent(cbxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDay)
                                    .addComponent(cbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblDate)
                                    .addComponent(lblDateView, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtnSaving)
                                    .addComponent(rbtnExpen)
                                    .addComponent(rbtnIncome)
                                    .addComponent(lblDiv))
                                .addGap(33, 33, 33)
                                .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblItem)
                                    .addComponent(cbxItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(tfdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblType)
                                    .addComponent(cbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMemo)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnReset))
                            .addGroup(paneWriteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnDeleteAll)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpload)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPane.addTab("작성", paneWrite);

        tarSearchView.setEditable(false);
        tarSearchView.setColumns(20);
        tarSearchView.setRows(5);
        tarSearchView.setTabSize(11);
        jScrollPane4.setViewportView(tarSearchView);

        cbxSearchYear1.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        cbxSearchYear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        cbxSearchMonth1.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        cbxSearchMonth1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cbxSearchYear2.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        cbxSearchYear2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        cbxSearchMonth2.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        cbxSearchMonth2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel1.setText("년");

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel2.setText("월");

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel3.setText("년");

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel4.setText("월");

        jLabel5.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        jLabel5.setText("~");

        btnSearchAll.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        btnSearchAll.setText("전체검색");
        btnSearchAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAllActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        btnSearch.setText("검색");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel7.setText("충동적 소비 : ");

        jLabel8.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel8.setText("계획적 소비 : ");

        jLabel9.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel9.setText("필수적 소비 : ");

        lblExpen1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblExpen3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblExpenPrice1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblExpenPrice2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblExpenPrice3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel15.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel15.setText("결산 : ");

        lblAllCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel20.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel20.setText("지출금액 : ");

        lblExpenPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel22.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel22.setText("수입금액 : ");

        lblIncomePrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnExit2.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btnExit2.setText("프로그램 종료");
        btnExit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit2ActionPerformed(evt);
            }
        });

        lblExpen2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout paneStatLayout = new javax.swing.GroupLayout(paneStat);
        paneStat.setLayout(paneStatLayout);
        paneStatLayout.setHorizontalGroup(
            paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneStatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneStatLayout.createSequentialGroup()
                        .addGroup(paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneStatLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(lblExpen2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneStatLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lblExpen1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneStatLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblExpen3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(paneStatLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(paneStatLayout.createSequentialGroup()
                                            .addComponent(jLabel22)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblIncomePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(paneStatLayout.createSequentialGroup()
                                            .addComponent(jLabel20)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblExpenPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(paneStatLayout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblAllCount, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addGroup(paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExpenPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblExpenPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblExpenPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneStatLayout.createSequentialGroup()
                        .addGap(0, 407, Short.MAX_VALUE)
                        .addComponent(cbxSearchYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbxSearchMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addGap(35, 35, 35)
                        .addComponent(cbxSearchYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbxSearchMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(96, 96, 96)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSearchAll)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        paneStatLayout.setVerticalGroup(
            paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneStatLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneStatLayout.createSequentialGroup()
                        .addGroup(paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lblExpen1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblExpen2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblExpen3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneStatLayout.createSequentialGroup()
                        .addComponent(lblExpenPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblExpenPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblExpenPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(227, 227, 227)
                .addGroup(paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(lblIncomePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(lblExpenPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(lblAllCount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 163, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneStatLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSearchYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbxSearchMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(cbxSearchYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbxSearchMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneStatLayout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit2))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        MainPane.addTab("통계", paneStat);

        tarListViewFilter.setEditable(false);
        tarListViewFilter.setColumns(20);
        tarListViewFilter.setRows(5);
        tarListViewFilter.setTabSize(19);
        jScrollPane6.setViewportView(tarListViewFilter);

        btnView.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        btnView.setText("조회");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        cbxFilter.setFont(new java.awt.Font("맑은 고딕", 0, 20)); // NOI18N
        cbxFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "최근 날짜 순", "오래된 날짜 순", "지출금액 높은 순", "지출금액 낮은 순", "유형별(가, 나, 다)" }));

        btnExit3.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btnExit3.setText("프로그램 종료");
        btnExit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneListLayout = new javax.swing.GroupLayout(paneList);
        paneList.setLayout(paneListLayout);
        paneListLayout.setHorizontalGroup(
            paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 718, Short.MAX_VALUE)
                .addComponent(cbxFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        paneListLayout.setVerticalGroup(
            paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneListLayout.createSequentialGroup()
                .addGap(0, 75, Short.MAX_VALUE)
                .addGroup(paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(cbxFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPane.addTab("내역", paneList);

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main.getContentPane());
        Main.getContentPane().setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1182, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("가계부 v0.1");

        btnLogin.setText("로그인");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnSignin.setText("회원가입");
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSignin, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginFrame.setBounds(0, 0, 500, 400);
        LoginFrame.setVisible(true);
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
        // TODO add your handling code here:
        dispose();
        SigninFrame.setBounds(0, 0, 550, 450);
        SigninFrame.setVisible(true);
    }//GEN-LAST:event_btnSigninActionPerformed

    private void btnSingFormSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingFormSigninActionPerformed
        // TODO add your handling code here:
        if (tfdNewName.getText().length() < 1 || tfdNewId.getText().length() < 1 || tfdNewPw.getText().length() < 1 || tfdNewPwCheck.getText().length() < 1 || tfdNewProperty.getText().length() < 1 ) {
            JOptionPane.showMessageDialog(null, "모든 항목을 입력해주세요.");
        } else {
            if (tfdNewPw.getText() != tfdNewPwCheck.getText()) {
                JOptionPane.showMessageDialog(null, "비밀번호를 확인해주세요.");
            } else { 
                strSQL = null;
                strSQL = "Insert Into User Values(";
                strSQL += "'" + tfdNewName.getText() + "', ";
                strSQL += "'" + tfdNewId.getText() + "', ";
                strSQL += "'" + tfdNewPw.getText() + "', "; 
                strSQL += "'" + Integer.parseInt(tfdNewProperty.getText()) + "')";
                try {
                    userDAO.dbOpen();
                    userDAO.DB_stmt.executeUpdate(strSQL);
                    userDAO.dbClose();
                } catch (Exception e) {
                    System.out.println("SQL Exception : " + e.getMessage());
                }
                SigninFrame.dispose();
                LoginFrame.setBounds(0, 0, 500, 400);
                LoginFrame.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnSingFormSigninActionPerformed

    private void btnNewIdCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewIdCheckActionPerformed
        // TODO add your handling code here:
        strSQL = "Select UserID From User;";
        try {
                userDAO.dbOpen();
                userDAO.DB_rs = userDAO.DB_stmt.executeQuery(strSQL);
                while (userDAO.DB_rs.next()) {
                    if(!userDAO.DB_rs.getString("UserID").equals(tfdNewPw.getText())) {
                        JOptionPane.showMessageDialog(null, "사용 가능한 아이디 입니다.");
                    } else {
                        JOptionPane.showMessageDialog(null, "사용 불가한 아이디 입니다.");
                    }
                }
                userDAO.dbClose();
            } catch (Exception e) {
                System.out.println("SQL Exception : " + e.getMessage());
            }
    }//GEN-LAST:event_btnNewIdCheckActionPerformed

    private void btnLogFromLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogFromLoginActionPerformed
        // TODO add your handling code here:
        if (tfdId.getText().length() < 1 || pwfPw.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "모든 항목을 입력해주세요.");
        } else {
            user.setUserID(tfdId.getText());
            user.setUserPassword(pwfPw.getText());
            int result = userDAO.login(tfdId.getText(), pwfPw.getText());
            if(result == 1) {
                user.setUserID(tfdId.getText());
                LoginFrame.dispose();
                Main.setBounds(0, 0, 1200, 750);
                Main.setVisible(true);

                strSQL = "select userName from user where userid = '" + user.getUserID() + "'";
                try {
                    userDAO.dbOpen();
                    userDAO.DB_rs = userDAO.DB_stmt.executeQuery(strSQL);
                    while (userDAO.DB_rs.next()) {
                        lblWelcome.setText(userDAO.DB_rs.getString("UserName") + "님, 안녕하세요");
                    }
                    userDAO.dbClose();
                } catch (Exception e) {
                    System.out.println("SQL Exception : " + e.getMessage());
                }
                dateChange();
            } else if (result == 0){ 
                JOptionPane.showMessageDialog(null, "비밀번호를 확인해주세요.");
            } else if (result == -2){ 
                JOptionPane.showMessageDialog(null, "DB 오류입니다.");
            } else if (result == -1){ 
                JOptionPane.showMessageDialog(null, "존재하지 않는 아이디입니다.");
            }
        }
    }//GEN-LAST:event_btnLogFromLoginActionPerformed

    private void rbtnIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnIncomeActionPerformed
        // TODO add your handling code here:
        if(rbtnIncome.isSelected() == true) {
            cbxItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "근로소득", "연금소득", "이자소득", "배당소득", "기타소득" }));
            cbxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "정기수입", "비정기수입" }));
            tfdPrice.setText("");
        } 
        
    }//GEN-LAST:event_rbtnIncomeActionPerformed

    private void rbtnExpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnExpenActionPerformed
        // TODO add your handling code here:
        if (rbtnExpen.isSelected() == true) {
            cbxItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "의류", "식비", "주거", "교육", "의료", "교통", "통신", "문화", "경조", "기타" }));
            cbxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "충동적소비", "계획적소비", "필수적소비" }));
            tfdPrice.setText("-");
        }
    }//GEN-LAST:event_rbtnExpenActionPerformed

    private void rbtnSavingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSavingActionPerformed
        // TODO add your handling code here:
        if (rbtnSaving.isSelected() == true) {
            cbxItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "주택청약", "정기적금", "자유적금", "기타" }));
            cbxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "적금"}));
            tfdPrice.setText("");
        }
    }//GEN-LAST:event_rbtnSavingActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tfdPrice.setText("");
        tarMemo.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        if(tfdPrice.getText().length() < 2 || tarMemo.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "모든 항목을 입력해주세요.");
        } else {
            strSQL = null;
            strSQL = "INSERT INTO accBook VALUES (";
            strSQL += "'" + user.getUserID() + "', ";
            strSQL += "'" + lblDateView.getText() + "', ";
            if(rbtnIncome.isSelected() == true) strSQL += "'" + rbtnIncome.getText() + "', ";
            if(rbtnExpen.isSelected() == true) strSQL += "'" + rbtnExpen.getText() + "', ";
            if(rbtnSaving.isSelected() == true) strSQL += "'" + rbtnSaving.getText() + "', ";
            strSQL += "'" + cbxItem.getSelectedItem().toString() + "', ";
            strSQL += "" + tfdPrice.getText() + ", ";
            strSQL += "'" + cbxType.getSelectedItem().toString() + "',";
            strSQL += "'" + tarMemo.getText() + "')";
            
            try {
                accDAO.dbOpen();
                accDAO.DB_stmt.executeUpdate(strSQL);
                strSQL = "Select UseDate, Division, Item, Price, UseType, Memo From accbook where UserId = '" + user.getUserID() + "'";
                tarTodayList.setText(accDAO.getDBData(strSQL));
                
                strSQL = "Select Item, Price, UseType From accBook where UserId = '" + user.getUserID() + "' and UseDate = '" + lblDateView.getText() + "' and Division = '" + rbtnIncome.getText() + "'";
                tarTodayIncome.setText(accDAO.getDBDataLeast(strSQL));
                
                 strSQL = "Select Item, Price, UseType From accBook where UserId = '" + user.getUserID() + "' and UseDate = '" + lblDateView.getText() + "' and Division = '" + rbtnExpen.getText() + "'";
                tarTodayExpen.setText(accDAO.getDBDataLeast(strSQL));
                
                accDAO.dbClose();
            } catch (Exception e) {
                System.out.println("SQL Exception : " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        try {
            accDAO.dbOpen();
            strSQL = "Select UseDate, Division, Item, Price, UseType, Memo From accBook where UserId = '" + user.getUserID() + "' and UseDate = '" + lblDateView.getText() + "'";
            tarTodayList.setText(accDAO.getDBData(strSQL));
            
            strSQL = "Select Item, Price, UseType From accBook where UserId = '" + user.getUserID() + "' and UseDate = '" + lblDateView.getText() + "' and Division = '" + rbtnIncome.getText() + "'";
            tarTodayIncome.setText(accDAO.getDBDataLeast(strSQL));
            
            strSQL = "Select Item, Price, UseType From accBook where UserId = '" + user.getUserID() + "' and UseDate = '" + lblDateView.getText() + "' and Division = '" + rbtnExpen.getText() + "'";
            tarTodayExpen.setText(accDAO.getDBDataLeast(strSQL));
            
            accDAO.dbClose();
        } catch (Exception e) {
            System.out.println("SQL Exception : " + e.getMessage());
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed
        // TODO add your handling code here:
        strSQL = "delete * from accBook where UserId = '" + user.getUserID() + "' and userDate = '" + lblDateView.getText() + "'";
        try {
            accDAO.dbOpen();
            accDAO.DB_stmt.executeUpdate(strSQL);
            accDAO.dbClose();
        } catch (Exception e) {
            System.out.println("SQL Exception : " + e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteAllActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void btnExit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExit3ActionPerformed

    private void cbxYearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxYearItemStateChanged
        // TODO add your handling code here:
        viewDateChange();
    }//GEN-LAST:event_cbxYearItemStateChanged

    private void cbxMonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMonthItemStateChanged
        // TODO add your handling code here:
        viewDateChange();
    }//GEN-LAST:event_cbxMonthItemStateChanged

    private void cbxDayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxDayItemStateChanged
        // TODO add your handling code here:
        viewDateChange();
    }//GEN-LAST:event_cbxDayItemStateChanged

    private void btnExit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExit2ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String date1 = cbxSearchYear1.getSelectedItem().toString() + "-" + cbxSearchMonth1.getSelectedItem().toString() + "-00";
        String date2 = cbxSearchYear2.getSelectedItem().toString() + "-" + cbxSearchMonth2.getSelectedItem().toString() + "-00";
        
        try {
            accDAO.dbOpen();
            strSQL = "select UseDate, Division, Item, Price, UseType, Memo from accBook where userId = '" + user.getUserID() + "' and useDate BETWEEN '" + date1 +"' and '" + date2 + "'";
            tarSearchView.setText(accDAO.getDBData(strSQL));
            
            strSQL = "select count(*) as Price from accBook where userId = '" + user.getUserID() + "' and UseType = '충동적소비' and useDate BETWEEN '" + date1 +"' and '" + date2 + "'";
            lblExpen1.setText(accDAO.lblExpen(strSQL) + " 건");
            
            strSQL = "select count(*) as Price from accBook where userId = '" + user.getUserID() + "' and UseType = '계획적소비' and useDate BETWEEN '" + date1 +"' and '" + date2 + "'";
            lblExpen2.setText(accDAO.lblExpen(strSQL) + " 건");
            
            strSQL = "select count(*) as Price from accBook where userId = '" + user.getUserID() + "' and UseType = '필수적소비' and useDate BETWEEN '" + date1 +"' and '" + date2 + "'";
            lblExpen3.setText(accDAO.lblExpen(strSQL) + " 건");
            
            strSQL = "select sum(Price) as Price from accBook where userId = '" + user.getUserID() + "' and UseType = '충동적소비' and useDate BETWEEN '" + date1 +"' and '" + date2 + "'";
            lblExpenPrice1.setText(accDAO.lblExpenPrice(strSQL) + " 원");
            
            strSQL = "select sum(Price) as Price from accBook where userId = '" + user.getUserID() + "' and UseType = '계획적소비' and useDate BETWEEN '" + date1 +"' and '" + date2 + "'";
            lblExpenPrice2.setText(accDAO.lblExpenPrice(strSQL) + " 원");
            
            strSQL = "select sum(Price) as Price from accBook where userId = '" + user.getUserID() + "' and UseType = '필수적소비' and useDate BETWEEN '" + date1 +"' and '" + date2 + "'";
            lblExpenPrice3.setText(accDAO.lblExpenPrice(strSQL) + " 원");
            
            strSQL = "select sum(Price) as Price from accBook where userId = '" + user.getUserID() + "' and Division = '수입'" + " and useDate BETWEEN '" + date1 +"' and '" + date2 + "'";
            lblIncomePrice.setText(accDAO.lblExpenPrice(strSQL) + " 원");
            
            strSQL = "select sum(Price) as Price from accBook where userId = '" + user.getUserID() + "' and Division = '지출'" + " and useDate BETWEEN '" + date1 +"' and '" + date2 + "'";
            lblExpenPrice.setText(accDAO.lblExpenPrice(strSQL) + " 원");
            
            strSQL = "select sum(Price) as Price from accBook where userId = '" + user.getUserID() + "' and Division = '지출' and Division = '수입'" + " and useDate BETWEEN '" + date1 +"' and '" + date2 + "'";
            lblAllCount.setText(accDAO.lblExpenPrice(strSQL) + " 원");
            
            accDAO.dbClose();
        } catch (Exception e) {
            System.out.println("SQL Exception : " + e.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearchAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAllActionPerformed
        // TODO add your handling code here:
        try {
            accDAO.dbOpen();
            strSQL = "Select UseDate, Division, Item, Price, UseType, Memo From accBook where UserId = '" + user.getUserID() + "'";
            tarSearchView.setText(accDAO.getDBData(strSQL));
            
            strSQL = "select count(*) as Price from accBook where userId = '" + user.getUserID() + "' and UseType = '충동적소비'";
            lblExpen1.setText(accDAO.lblExpen(strSQL) + " 건");
            
            strSQL = "select count(*) as Price from accBook where userId = '" + user.getUserID() + "' and UseType = '계획적소비'";
            lblExpen2.setText(accDAO.lblExpen(strSQL) + " 건");
            
            strSQL = "select count(*) as Price from accBook where userId = '" + user.getUserID() + "' and UseType = '필수적소비'";
            lblExpen3.setText(accDAO.lblExpen(strSQL) + " 건");
            
            strSQL = "select sum(Price) as Price from accBook where userId = '" + user.getUserID() + "' and UseType = '충동적소비'";
            lblExpenPrice1.setText(accDAO.lblExpenPrice(strSQL) + " 원");
            
            strSQL = "select sum(Price) as Price from accBook where userId = '" + user.getUserID() + "' and UseType = '계획적소비'";
            lblExpenPrice2.setText(accDAO.lblExpenPrice(strSQL) + " 원");
            
            strSQL = "select sum(Price) as Price from accBook where userId = '" + user.getUserID() + "' and UseType = '필수적소비'";
            lblExpenPrice3.setText(accDAO.lblExpenPrice(strSQL) + " 원");
            
            strSQL = "select sum(Price) as Price from accBook where userId = '" + user.getUserID() + "' and Division = '수입'";
            lblIncomePrice.setText(accDAO.lblExpenPrice(strSQL) + " 원");
            
            strSQL = "select sum(Price) as Price from accBook where userId = '" + user.getUserID() + "' and Division = '지출'";
            lblExpenPrice.setText(accDAO.lblExpenPrice(strSQL) + " 원");
            
            strSQL = "select sum(Price) as Price from accBook where userId = '" + user.getUserID() + "' and Division != '저축'";
            lblAllCount.setText(accDAO.lblExpenPrice(strSQL) + " 원");
            
            accDAO.dbClose();
        } catch (Exception e) {
            System.out.println("SQL Exception : " + e.getMessage());
        }
    }//GEN-LAST:event_btnSearchAllActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        if(cbxFilter.getSelectedItem().toString().equals("최근 날짜 순")) strSQL = "select UseDate, Division, Item, Price, UseType, Memo From accBook where UserId = '" + user.getUserID() + "' order by UseDate desc";
        if(cbxFilter.getSelectedItem().toString().equals("오래된 날짜 순")) strSQL = "select UseDate, Division, Item, Price, UseType, Memo From accBook where UserId = '" + user.getUserID() + "' order by UseDate asc";
        if(cbxFilter.getSelectedItem().toString().equals("지출금액 높은 순")) strSQL = "select UseDate, Division, Item, Price, UseType, Memo From accBook where UserId = '" + user.getUserID() + "' order by Price asc";
        if(cbxFilter.getSelectedItem().toString().equals("지출금액 낮은 순")) strSQL = "select UseDate, Division, Item, Price, UseType, Memo From accBook where UserId = '" + user.getUserID() + "' order by Price desc";
        if(cbxFilter.getSelectedItem().toString().equals("유형별(가, 나, 다)")) strSQL = "select UseDate, Division, Item, Price, UseType, Memo From accBook where UserId = '" + user.getUserID() + "' order by Item asc";
            
        try {
            accDAO.dbOpen();
            tarListViewFilter.setText(accDAO.getDBData(strSQL));
            accDAO.dbClose();
        } catch (Exception e) {
            System.out.println("SQL Exception : " + e.getMessage());
        }
    }//GEN-LAST:event_btnViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame LoginFrame;
    private javax.swing.JFrame Main;
    private javax.swing.JTabbedPane MainPane;
    private javax.swing.JFrame SigninFrame;
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnExit2;
    private javax.swing.JButton btnExit3;
    private javax.swing.ButtonGroup btnGrpDivision;
    private javax.swing.JButton btnLogFromLogin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNewIdCheck;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchAll;
    private javax.swing.JButton btnSignin;
    private javax.swing.JButton btnSingFormSignin;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cbxDay;
    private javax.swing.JComboBox<String> cbxFilter;
    private javax.swing.JComboBox<String> cbxItem;
    private javax.swing.JComboBox<String> cbxMonth;
    private javax.swing.JComboBox<String> cbxSearchMonth1;
    private javax.swing.JComboBox<String> cbxSearchMonth2;
    private javax.swing.JComboBox<String> cbxSearchYear1;
    private javax.swing.JComboBox<String> cbxSearchYear2;
    private javax.swing.JComboBox<String> cbxType;
    private javax.swing.JComboBox<String> cbxYear;
    private javax.swing.JLabel choiceDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblAllCount;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateView;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblDiv;
    private javax.swing.JLabel lblExpen1;
    private javax.swing.JLabel lblExpen2;
    private javax.swing.JLabel lblExpen3;
    private javax.swing.JLabel lblExpenPrice;
    private javax.swing.JLabel lblExpenPrice1;
    private javax.swing.JLabel lblExpenPrice2;
    private javax.swing.JLabel lblExpenPrice3;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIncomePrice;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblMemo;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JLabel lblNewId;
    private javax.swing.JLabel lblNewName;
    private javax.swing.JLabel lblNewProperty;
    private javax.swing.JLabel lblNewPw;
    private javax.swing.JLabel lblNewPwCheck;
    private javax.swing.JLabel lblPw;
    private javax.swing.JLabel lblTodayList;
    private javax.swing.JLabel lblTodayList1;
    private javax.swing.JLabel lblTodayList2;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblYear;
    private javax.swing.JPanel paneList;
    private javax.swing.JPanel paneStat;
    private javax.swing.JPanel paneWrite;
    private javax.swing.JPasswordField pwfPw;
    private javax.swing.JRadioButton rbtnExpen;
    private javax.swing.JRadioButton rbtnIncome;
    private javax.swing.JRadioButton rbtnSaving;
    private javax.swing.JTextArea tarListViewFilter;
    private javax.swing.JTextArea tarMemo;
    private javax.swing.JTextArea tarSearchView;
    private javax.swing.JTextArea tarTodayExpen;
    private javax.swing.JTextArea tarTodayIncome;
    private javax.swing.JTextArea tarTodayList;
    private javax.swing.JTextField tfdId;
    private javax.swing.JTextField tfdNewId;
    private javax.swing.JTextField tfdNewName;
    private javax.swing.JTextField tfdNewProperty;
    private javax.swing.JTextField tfdNewPw;
    private javax.swing.JTextField tfdNewPwCheck;
    private javax.swing.JTextField tfdPrice;
    // End of variables declaration//GEN-END:variables
}
